blog/urls.py
from django.urls import path
from blog.views import register_subscriber, unsubscribe

urlpatterns = [
    path("subscribe/", register_subscriber, name="register_blog_subscriber"),
    path("unsubscribe/", unsubscribe, name="unsubscribe_blog"),
]

blog/models.py
from django.db import models
from django import forms

from wagtail.core.models import Page, Orderable
from wagtail.core.fields import StreamField, RichTextField
from wagtail.admin.edit_handlers import (
    FieldPanel,
    InlinePanel,
    MultiFieldPanel,
    StreamFieldPanel,
)
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index
from wagtail.snippets.models import register_snippet
from modelcluster.fields import ParentalKey, ParentalManyToManyField
from modelcluster.contrib.taggit import ClusterTaggableManager
from taggit.models import TaggedItemBase
from blog.blocks import TwoImageBlock
from wagtail.core import blocks
from wagtail.images.blocks import ImageChooserBlock


@register_snippet
class BlogCategory(models.Model):
    name = models.CharField(max_length=255)
    icon = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )

    panels = [
        FieldPanel("name"),
        ImageChooserPanel("icon"),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "blog categories"


class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        "BlogPage", related_name="tagged_items", on_delete=models.CASCADE
    )


class BlogIndexPage(Page):
    intro = RichTextField(blank=True)

    content_panels = Page.content_panels + [FieldPanel("intro", classname="full")]

    def get_context(self, request):
        context = super().get_context(request)

        # Get blog entries
        blog_entries = BlogPage.objects.child_of(self).live()

        # Filter by tag
        tag = request.GET.get("tag")
        if tag:
            blog_entries = blog_entries.filter(tags__name=tag)

        context["blog_entries"] = blog_entries.order_by("-date")
        return context


class BlogPage(Page):

    author = models.CharField("Author", max_length=150)

    date = models.DateField("Post date")

    body = StreamField(
        [
            ("title", blocks.CharBlock(classname="blog-title")),
            ("paragraph", blocks.RichTextBlock()),
            ("image", ImageChooserBlock()),
            ("two_images", TwoImageBlock()),
        ]
    )

    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)

    categories = ParentalManyToManyField("blog.BlogCategory", blank=True)

    def blog_preview(self):
        for block in self.body:
            if block.block_type == "paragraph":
                return block.value
        else:
            return "No Preview for this blog"

    def preview_image(self):
        for block in self.body:
            if block.block_type == "image":
                return block.value
            elif block.block_type == "two_images":
                return block.value["left_image"]
        else:
            return None

    search_fields = Page.search_fields + [
        index.SearchField("title"),
        index.SearchField("author"),
        index.SearchField("body"),
        index.RelatedFields(
            "tags",
            [
                index.RelatedFields(
                    "tag", [index.SearchField("name", partial_match=True, boost=10)],
                )
            ],
        ),
        index.RelatedFields("categories", [index.SearchField("name"),]),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel(
            [
                FieldPanel("author"),
                FieldPanel("date"),
                FieldPanel("tags"),
                FieldPanel("categories", widget=forms.CheckboxSelectMultiple),
            ],
            heading="Blog information",
        ),
        StreamFieldPanel("body"),
    ]


class BlogPageGalleryImage(Orderable):
    page = ParentalKey(
        BlogPage, on_delete=models.CASCADE, related_name="gallery_images"
    )
    image = models.ForeignKey(
        "wagtailimages.Image", on_delete=models.CASCADE, related_name="+"
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel("image"),
        FieldPanel("caption"),
    ]

blog/models/blog_category.py
from django.db import models
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.models import register_snippet


@register_snippet
class BlogCategory(models.Model):

    name = models.CharField(max_length=255)

    icon = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )

    panels = [
        FieldPanel("name"),
        ImageChooserPanel("icon"),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "blog categories"

blog/models/blog_index_page.py
from django.db import models
from django import forms
from django.conf import settings

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel

from .blog_page import BlogPage


class BlogIndexPage(Page):

    intro = RichTextField(blank=True)

    content_panels = Page.content_panels + [FieldPanel("intro", classname="full")]

    def get_context(self, request):
        context = super().get_context(request)

        # Get blog entries
        blog_entries = BlogPage.objects.child_of(self).live()

        # Filter by tag
        tag = request.GET.get("tag")
        if tag:
            blog_entries = blog_entries.filter(tags__name=tag)

        # category
        category = request.GET.get("category")
        if category:
            blog_entries = blog_entries.filter(categories__name=category)

        context["blog_entries"] = blog_entries.order_by("-date")
        return context

blog/models/blog_page.py
from django.db import models
from django import forms

from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.admin.edit_handlers import (
    FieldPanel,
    MultiFieldPanel,
    StreamFieldPanel,
)
from wagtail.search import index
from modelcluster.fields import ParentalManyToManyField
from modelcluster.contrib.taggit import ClusterTaggableManager
from blog.blocks import TwoImageBlock, ImageCaptionBlock
from wagtail.core import blocks
from wagtail.images.blocks import ImageChooserBlock

from .blog_tag import BlogPageTag


class BlogPage(Page):

    author = models.CharField("Author", max_length=150)

    date = models.DateField("Post date")

    body = StreamField(
        [
            ("title", blocks.CharBlock(classname="blog-title")),
            ("paragraph", blocks.RichTextBlock()),
            ("image", ImageChooserBlock()),
            ("image_w_caption", ImageCaptionBlock()),
            ("two_images", TwoImageBlock()),
        ]
    )

    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)

    categories = ParentalManyToManyField("blog.BlogCategory", blank=True)

    def blog_preview(self):
        for block in self.body:
            if block.block_type == "paragraph":
                return block.value
        else:
            return "No Preview for this blog"

    def preview_image(self):
        for block in self.body:
            # IF we have a block that is the image type
            if block.block_type == "image":
                return block.value
            # If we have a block that is an image with a caption
            elif block.block_type == "image_w_caption":
                return block.value["image"]
            # If we have a two image block
            elif block.block_type == "two_images":
                # Get the left image stream block
                left_image = block.value["left_image"]
                # If the first image (because there should only ever be one)
                # in the left image is an image block
                if left_image[0].block_type == "image":
                    return left_image[0].value
                # If the first image (because there should only ever be one)
                # in the left image is an image block with a caption, grap the image
                return left_image[0].value["image"]
        else:
            return None

    search_fields = Page.search_fields + [
        index.SearchField("title"),
        index.SearchField("author"),
        index.SearchField("body"),
        index.RelatedFields(
            "tags",
            [
                index.RelatedFields(
                    "tag", [index.SearchField("name", partial_match=True, boost=10)],
                )
            ],
        ),
        index.RelatedFields("categories", [index.SearchField("name"),]),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel(
            [
                FieldPanel("author"),
                FieldPanel("date"),
                FieldPanel("tags"),
                FieldPanel("categories", widget=forms.CheckboxSelectMultiple),
            ],
            heading="Blog information",
        ),
        StreamFieldPanel("body"),
    ]

blog/models/blog_subscriber.py
from django.db import models
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.snippets.models import register_snippet


@register_snippet
class BlogSubscriber(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )

    raw_email = models.EmailField(null=True, blank=True)

    panels = [
        FieldPanel("user"),
        FieldPanel("raw_email"),
    ]

    def send_registration_confirmation(self):
        msg_plain = render_to_string(
            "blog/subscription_confirmation.txt", {"token": self.email}
        )
        msg_html = render_to_string(
            "blog/subscription_confirmation.html", {"token": self.email}
        )
        send_mail(
            "Emma Dozen Grapes Subscription Confirmation",
            msg_plain,
            settings.DEFAULT_FROM_EMAIL,
            [self.email],
            html_message=msg_html,
        )

    @property
    def email(self) -> str:
        return self.raw_email if not self.user_id else self.user.email

    def __str__(self):
        return self.email

blog/models/blog_tag.py
from django.db import models

from modelcluster.fields import ParentalKey
from taggit.models import TaggedItemBase


class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        "BlogPage", related_name="tagged_items", on_delete=models.CASCADE
    )

blog/forms/blog_subscriber_register.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from blog.models import BlogSubscriber


class BlogSubscriberRegisterForm(forms.Form):

    email = forms.EmailField(required=False)

    user = forms.IntegerField(min_value=1, required=False)

    next_location = forms.CharField(max_length=150, initial="/blog", required=False)

    def clean(self):
        cleaned_data = super().clean()

        if not cleaned_data.get("email", None) and not cleaned_data.get("user", None):
            raise ValidationError(
                "You must specify either an email or user to subscribe"
            )

        if cleaned_data.get("user"):
            try:
                cleaned_data["user"] = User.objects.get(cleaned_data.get("user"))
            except User.DoesNotExist:
                raise ValidationError("You must specify a valid user ID")

        return cleaned_data

    def save(self) -> BlogSubscriber:
        kwargs = {}
        if self.cleaned_data["user"]:
            kwargs["user"] = self.cleaned_data["user"]
        else:
            kwargs["raw_email"] = self.cleaned_data["email"]

        sub, created = BlogSubscriber.objects.get_or_create(**kwargs)
        if created:
            sub.send_registration_confirmation()

        return sub

blog/views.py
from django.db import models
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.tokens import PasswordResetTokenGenerator


from blog.forms import BlogSubscriberRegisterForm
from blog.models import BlogSubscriber, BlogPage
from django.utils import timezone

# Create your views here.


def register_subscriber(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = BlogSubscriberRegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Successfully signed up for email subscription! You should receive a verification email shortly",
            )
    else:
        form = BlogSubscriberRegisterForm()

    redirect_url = form["next_location"].value() or form["next_location"].initial

    return redirect(redirect_url)


def unsubscribe(request):
    token = request.GET.get("token", None)
    if not token:
        return redirect("/blog")
    try:
        subscriber = BlogSubscriber.objects.filter(
            models.Q(raw_email=token) | models.Q(user__email=token)
        )
        subscriber.delete()
    except BlogSubscriber.DoesNotExist:
        pass

    messages.success(
        request, "You have successfully unsubscribed to Emma Dozen Grapes Newsletter"
    )
    return redirect("/blog")

blog/templates/blog/blog_index_page.html
{% extends "base.html" %}

{% load wagtailcore_tags  wagtailimages_tags %}

{% block body_class %}template-blogindexpage{% endblock %}

{% block content %}
    <div class="container-fluid align-items-center">
        <h1 class="header alysa-font">{{ page.title }}</h1>
        <div class="container">
            <div class="row">
                {% for post in blog_entries %}
                    {% with post=post.specific %}
                        <div class="col-md-4 col-sm-6 col-xs-12 mb-2">
                            <div class="card">
                                {% with post.preview_image as main_image %}
                                    {% if main_image %}
                                    {% comment %} <div class="d-flex flex-row justify-content-center"> {% endcomment %}
                                        {% image main_image original as card_image %}
                                        <img src="{{card_image.url}}" class="card-img-top" />
                                    {% comment %} </div> {% endcomment %}
                                        
                                    {% endif %}
                                {% endwith %}
                                
                                <div class="card-body">
                                <h2 class="card-title loraitalic-font"><a href="{% pageurl post %}">{{ post.title }}</a></h2>
                                <p class="card-text lora-font">{{ post.intro }}</p>
                                <p class="card-text lora-font">
                                    <i class="fas fa-calendar mr-2"></i>
                                    {{ post.date }}
                                </p>
                                <div class="row">
                                    <div class="col-12 d-flex flex-row flex-wrap">
                                        {% for category in post.categories.all %}
                                            <a href="/blog?category={{ category|urlencode }}" class="tag-link">
                                                <div class="tag loraitalic-font">
                                                    <i class="fas fa-tag mr-1 d-flex align-items-center justify-content-center"></i>
                                                    {{ category }}
                                                </div>
                                            </a>
                                        {% endfor %}
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    {% endwith %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags static comments %}

{% block body_class %}template-blogpage{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog_page.css' %}">
{% endblock %}

{% block content %}
<div class="container align-items-center">

    <h1 class="header loraitalic-font blog-header">{{page.title}}</h1>

    <p class="text-muted mb-2">{{page.date}}</p>
    <p class="text-muted mt-2">{{page.author}}</p>
    <div class="row">
        <div class="col-12 d-flex flex-row flex-wrap">
            {% for category in page.categories.all %}
                <a href="/blog?category={{ category }}" class="tag-link">
                    <div class="tag loraitalic-font">
                        <i class="fas fa-tag mr-1 d-flex align-items-center justify-content-center"></i>
                        {{ category }}
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>


    {% with blocks=self.body %}
        {% for block in blocks %}
                {%if block.block_type == 'image'%}
                    <div class="row">
                        <div class="col-12">
                            {% image block.value width-800 as photo %}
                            <img src="{{photo.url}}" height="auto" width="100%" style="padding-top: 15px; padding-bottom: 15px"/>
                        </div>
                    </div>
                {% else %}
                    <section class="block-{{ block.block_type }} pb-3">
                        {{ block }}
                    </section>
                {% endif %}
        {% endfor %}
    {% endwith %}

    {% if page.tags.all.count %}
        <div class="row my-5">
            <div class="col-12 d-flex flex-row flex-wrap">
                {% for tag in page.tags.all %}
                    <a href="/blog?tag={{ tag }}" class="tag-link">
                        <div class="tag loraitalic-font">
                            <i class="fas fa-tag mr-1 d-flex align-items-center justify-content-center"></i>
                            {{ tag }}
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <hr style="margin: 0 -15px"/>
    
    <div class="row my-3">
        <div class="col-12">
            <h1 class="alysa-font" style="font-size: 4em; text-align: center">comments</h1>
        </div>
        <div class="col-12 comment">
            {% get_comment_form for page as form %}
            <form action="{% comment_form_target %}" method="post" novalidate class="needs-validation">
                {% csrf_token %}
                <div class="row mb-2">
                    <div class="col-md-6 col-sm-12 form-group">
                        <input id="id_name" class="form-control" placeholder="Name" required="true" name="name" maxlength="50"/>
                        <div class="invalid-feedback">
                            Please enter a valid display name
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12 form-group">
                        <input id="id_email" class="form-control" placeholder="Email" required="true" type="email" name="email"/>
                        <div class="invalid-feedback">
                            Please enter a valid email
                        </div>
                        <div class="container-fluid p-0">
                            <small id="passwordHelpBlock" class="form-text text-muted">
                                Your email will not be displayed publicly
                            </small>
                        </div>
                        
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-12 form-group">
                        <textarea id="id_comment" class="form-control" placeholder="Comment" required="true" name="comment" maxlength="3000"></textarea>
                        <div class="invalid-feedback">
                            Please enter a comment
                        </div>
                    </div>
                </div>
                
                <input id="id_url" placeholder="Website" value="" name="url"/>
                {{ form.honeypot }}
                {{ form.content_type }}
                {{ form.object_pk }}
                {{ form.timestamp }}
                {{ form.security_hash }}
                <input type="hidden" name="next" value="{% pageurl page %}" />
                <input class="btn primary-button" type="submit" name="submit" value="Post">
            </form>
        </div>
    </div>

    {% get_comment_list for page as comment_list %}
    <div class="row">

        {% for comment in comment_list %}
            <div class="col-12 mb-2">
                <p class="text-muted mb-0">{{comment.user_name}}</p>
                <p class="text-muted mt-0"> {{comment.submit_date|date:'DATE_FORMAT'}} </p>
                <p class="text-break">
                    {{comment.comment}}
                <p>

                {% if not forloop.last %}
                    <hr />
                {% endif %}
            </div>
        {% endfor %}

    </div>
    
    
</div>
{% endblock %}

{% block subscribe %}{% endblock %}

blog/templates/blog/subscribe.html
<div class="container-fluid mt-3 pt-2" style="background-color: rgb(253 251 251); margin-bottom: -1rem !important;">
    <h1 class="text-center alysa-font">subscribe</h1>
    <div class="row justify-content-center align-items-center">
        <form class="form-group row align-items-center needs-validation" action="/blog/subscribe/" method="post">
            {% csrf_token %}
            <div class="col-md-auto col-sm-12">
                <input id="id_email" type="email" class="form-control" placeholder="Email Address" name="email" required="true">
            </div>
            <div class="col-md-auto col-sm-12 d-flex align-items-center justify-content-center py-2">
                <button type="submit" class="btn primary-button">Submit</button>
            </div>
        </form>
    </div>
</div>